WIP: Refactor LocalMediaPlayer to Kotlin, fix #390
ultrasonic/ultrasonic pull request #405
Opened 2021-03-24 15:46 UTC by tzugen

While refactoring I found three weird lines, which could be actually bugs, or just hacks without comment. 
I annotated them with #FIXME , please check them out...

2021-03-24 15:58 UTC, tzugen commented
What is the idea with checkstyle and too long lines if the method signature is that long?
I could abbreviate the parameters, but that doesn't make things more readable or understandable, no?

`    private inner class BufferTask(private val downloadFile: DownloadFile, private val position: Int) : CancellableTask() {`

2021-03-24 21:16 UTC, tzugen commented
The static analysis fails only because of the //FIXME comments I added ;)

2021-03-25 08:20 UTC, nitehu requested changes
Wow nice work, thank you!
I've added a few comments for the FIXMEs, please check if those make sense to you.
Otherwise, the review was OK.

2021-03-25 08:20 UTC, nitehu commented on ultrasonic/src/main/kotlin/org/moire/ultrasonic/service/LocalMediaPlayer.kt
> +        nextMediaPlayer = oldPlayer
I think the original logic was that there are two instances of initialized MediaPlayers, while one is playing the other is being prepared. Here the two are swapped (using a temp variable).
This seems to be no longer necessary as the nextPlayer is always recreated as a new MediaPlayer... 
You may remove it and see if it breaks anything.

2021-03-25 08:20 UTC, nitehu commented on ultrasonic/src/main/kotlin/org/moire/ultrasonic/service/LocalMediaPlayer.kt
> +        attachHandlersToPlayer(mediaPlayer, currentPlaying!!, false)
I think after the setCurrentPlaying() call the currentPlaying and nextPlaying will be the same.
Change this as you like (or just add a comment for anyone reads the code next)

2021-03-25 08:20 UTC, nitehu commented on ultrasonic/src/main/kotlin/org/moire/ultrasonic/service/LocalMediaPlayer.kt
> +            audioManager.unregisterRemoteControlClient(remoteControlClient)
This seems to be a workaround, and I'm not sure for what reason it was added. I've found this nugget of wisdom by googleing a bit: 
"You must register your RemoteControlDisplay every time when the View which displays metadata is shown to the user. This is because 4.2.2 and lower versions support only one RemoteControlDisplay, and if system will decide to register it's own RCD, your RCD will be unregistered automatically."
This may explain it, if it is true for RemoteControlClients too.
As Ultrasonic supports older Androids, I think it is enough to add a comment here for anyone reads the code next.

2021-03-25 16:23 UTC, tzugen commented on ultrasonic/src/main/kotlin/org/moire/ultrasonic/service/LocalMediaPlayer.kt
> +        nextMediaPlayer = oldPlayer
Seems to work ok, if removed :)

2021-03-25 16:24 UTC, tzugen commented on ultrasonic/src/main/kotlin/org/moire/ultrasonic/service/LocalMediaPlayer.kt
> +        attachHandlersToPlayer(mediaPlayer, currentPlaying!!, false)
Yep, i changed it to be more understandable.

2021-03-25 16:24 UTC, tzugen commented on ultrasonic/src/main/kotlin/org/moire/ultrasonic/service/LocalMediaPlayer.kt
> +            audioManager.unregisterRemoteControlClient(remoteControlClient)
ok!

2021-03-25 16:33 UTC, tzugen commented
Ok, thanks for the comments.

I uncovered another bug, probably in MediaPlayerService #406 
Afterwords I've been listening to music most of the day and it is stable so far.

2021-03-25 18:55 UTC, nitehu commented
Ok so I think I've found an issue. When Ultrasonic is started, it starts the playback immediately, which is not how it woked before.

It is regarding the change in MediaPlayerControllerImpl (doPlay -> play). Play calls bufferAndPlay, which starts a BufferTask, and when that's completed, the playback is started instantly (practically this happens when Ultrasonic is started)
Originally doPlay had a "start" parameter which was used to signal whether autostart is necessary, at Ultrasonic startup this is false by default, so the playback wasn't started.

Could you please check this?

2021-03-25 19:18 UTC, tzugen commented
> Ok so I think I've found an issue. When Ultrasonic is started, it starts the playback immediately, which is not how it woked before.
> 
> It is regarding the change in MediaPlayerControllerImpl (doPlay -> play). Play calls bufferAndPlay, which starts a BufferTask, and when that's completed, the playback is started instantly (practically this happens when Ultrasonic is started)
> Originally doPlay had a "start" parameter which was used to signal whether autostart is necessary, at Ultrasonic startup this is false by default, so the playback wasn't started.
> 
> Could you please check this?

Do you know the exact steps to reproduce? I can't seem to do it. The restore method in MediaPlayerControllerImpl gets passed an AutoPlay boolean, and this boolean is passed down the chain...

2021-03-25 19:20 UTC, tzugen commented
Ah, i got it reproduce.

2021-03-25 19:38 UTC, tzugen commented
The interesting thing is that in BufferTask doPlay() was called also before with autoPlay set to true, not respecting the value from restore(). 
Funny that that popped up now :shrug:

2021-03-27 18:32 UTC, nitehu commented
Thank you, it seems to be OK now. I'll test it for 1-2 days to see if everything else is fine too.

2021-03-27 18:32 UTC, nitehu approved these changes

2021-03-29 07:06 UTC, nitehu commented
I think there's another issue, suddenly Ultrasonic was throwing an exception when I pressed play, and playback wouldn't start.
The exception was
```
08:19:11.396: I LocalMediaPlayer Preparing media player 
08:19:11.398: W LocalMediaPlayer Media player error
java.io.IOException: setDataSourceFD failed.: status=0x80000000
	at android.media.MediaPlayer._setDataSource(Native Method)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1356)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1339)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1278)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1239)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1204)
	at org.moire.ultrasonic.service.LocalMediaPlayer.doPlay(LocalMediaPlayer.kt:521)
	at org.moire.ultrasonic.service.LocalMediaPlayer.access$doPlay(LocalMediaPlayer.kt:42)
	at org.moire.ultrasonic.service.LocalMediaPlayer$BufferTask.execute(LocalMediaPlayer.kt:728)
	at org.moire.ultrasonic.util.CancellableTask$1.run(CancellableTask.java:84)
 java.io.IOException: setDataSourceFD failed.: status=0x80000000

```
Of course as soon as I've attached the debugger it fixed itself, so I'm trying to reproduce it now. I was listening to some music in the car when it froze, so maybe it was related to start/stop by bluetooth disconnect/reconnects.

2021-03-29 09:59 UTC, nitehu commented
I think I've found what causes #406 .
LocalMediaPlayer is a singleton in the DI, so the same instance is used everywhere in Ultrasonic while it runs.
That's why in the original file the mediaPlayer was initialized in the onCreate function.
When you moved the initialization in the constructor, that broke, since there is a single instance of LocalMediaPlayer and the constructor will only run once.
Please fix this (e.g. by moving back the initialization of mediaPlayer to the onCreate)

2021-03-30 09:00 UTC, tzugen commented
Ok, I understand the Singleton concept now. 
But I am not sure if moving the init of mediaPlayer to onCreate is the right solution.

It feels semantically wrong that the class has an onDestroy function, but is never actually destroyed, so the method onCreate and onDestroy are actually more an init() and cleanup() method.

I haven't wrapped my head around it completely, but there are two approaches that look saner to me:
* Rename the onCreate/onDestroy methods to something semantically more meaningful, and init/release mediaPlayer there.
* Maybe better?: Make  LocalMediaPlayer a scoped instance, so that it follows the lifecycle of the service ( https://insert-koin.io/docs/reference/koin-core/scopes/ )

2021-03-30 09:32 UTC, nitehu commented
I just suggested to move it back to the onCreate because that is how it was in the Java version, and sometimes there are legacy things which will fall apart quickly if we try to change them (this doesn't mean that they absolutely shouldn't be changed, but they will require a lot more work and testing, and these kind of things better done in small, focused steps).

For example, if you try to change LocalMediaPlayer to a scoped instance, you'll find that it is referenced from MediaPlayerControllerImpl and Downloader, which are also singletons, and the UI uses them so can't be scoped, and this PR will just get bigger and bigger. 

I however absolutely agree that the onCreate/onDestroy naming is a bit misleading as they suggest Android manages its lifecycle somehow, so it would be nice to change them to something more understandable.

And of course many kudos to you if later when you have time (and patience) you'll try to cut order into this legacy spaghetti by refactoring the media player parts in one or more separate PRs 😊

2021-03-30 09:57 UTC, tzugen commented
Ok cool, thanks :)
I will rename the methods, but make them work like before.

I have opened a new bug (#409 ) because I think these issues would be worth discussing more,
but not as part of this PR

2021-03-30 12:54 UTC, tzugen commented
Ok, renamed. I assign a new MediaPlayer instance after release, instead of making the property nullable, because in a future PR, I would have probably reverted it again. Hope that is ok as well :)

2021-04-01 08:35 UTC, ogarcia approved these changes
LGTM. @nitehu if you don't see more inconvenience you can merge this pull request

2021-04-01 08:55 UTC, nitehu commented
Thank you! Just that one exception above bothers me. 
We are going on a trip on the weekend and we'll use Ultrasonic a lot, if I still can't reproduce it I'll merge this PR.

2021-04-06 05:49 UTC, merged