Make all preference operations context-free
ultrasonic/ultrasonic pull request #477
Opened 2021-05-09 06:48 UTC by tzugen

(use the application context for them)

2021-05-10 13:30 UTC, nitehu requested changes
Nice work! The code is a lot clearer now again.
However, you've removed nullable ("?") from a few parameters in RESTMusicService for functions that can be called with null from java. This currently causes an exception for me.
Please check these parameters again.

2021-05-10 13:30 UTC, nitehu commented on ultrasonic/src/main/kotlin/org/moire/ultrasonic/service/RESTMusicService.kt
> +        musicFolderId: String,
It seems musicFolderId can be null when it isn't selected. Currently this throws this exception for me:

```
W/CommunicationErrorHandler$Companion: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter musicFolderId
        at org.moire.ultrasonic.service.RESTMusicService.getIndexes(Unknown Source:6)
        at org.moire.ultrasonic.service.CachedMusicService.getIndexes(CachedMusicService.java:139)
        at org.moire.ultrasonic.fragment.ArtistListModel$loadFromServer$2.invokeSuspend(ArtistListModel.kt:94)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

2021-05-11 10:00 UTC, tzugen commented
Seems like the IDE has a bug in Refactor>Change Signature, when the interface is in Java, and the implementation is in Kotlin,
then it derives the nullability wrong or something.

I fixed it :+1:

2021-05-11 10:34 UTC, nitehu approved these changes
Looking good now!

2021-05-11 10:34 UTC, merged