Introduce new Generic Fragments, ViewModels, and Adapters for the display of API data.
ultrasonic/ultrasonic pull request #493
Opened 2021-05-15 14:21 UTC by tzugen

* Splits former SelectAlbumFragment into separate fragments for Albums and general collections of tracks
* Renames and refactors SelectArtist view to extend the new Generic classes
* Adds error handling (Fixes #484)
* Adds EndlessScrolling capabilities to all Album Lists :partying_face: 
* Uses RecyclerViews and LiveData for performance and in-memory caching
* Refreshes the UI to be aligned with the ArtistList UI
* Add a new GenericEntry to the domain data classes, and make other types extend it

2021-05-15 14:25 UTC, tzugen commented
It's the first time I used the ConstraintLayout. Let me know if it looks off somewhere.
Also: 
Generics are really nice. Read about the here: https://kotlinlang.org/docs/generics.html

2021-05-15 17:58 UTC, ogarcia commented
> * Adds EndlessScrolling capabilities to all Album Lists 🥳

🎉🎉🎉

2021-05-16 15:44 UTC, tzugen commented
Rebased on master.

2021-05-16 17:20 UTC, nitehu requested changes
Great job! The endless scrolling works very good, and I didn't find any noticable problems with the layout.
There are some minor issues, mostly with the folder selector. Could you please check these?

2021-05-16 17:20 UTC, nitehu commented on ultrasonic/src/main/kotlin/org/moire/ultrasonic/fragment/AlbumRowAdapter.kt
> + * Creates a Row in a RecyclerView which contains the details of an Artist
I think "Artist" here is a copy/paste error (and in the copyright header too)

2021-05-16 17:20 UTC, nitehu commented on ultrasonic/src/main/kotlin/org/moire/ultrasonic/fragment/AlbumListModel.kt
> +    private fun sortableCollection(albumListType: String): Boolean {
The name of this confused me for a second, maybe isCollectionSortable would be better?

2021-05-16 17:20 UTC, nitehu commented on ultrasonic/src/main/kotlin/org/moire/ultrasonic/fragment/TrackCollectionFragment.kt
> +        println("CoroutineExceptionHandler got $exception")
I think this println was supposed to be a Timber log write...

2021-05-16 17:20 UTC, nitehu commented on ultrasonic/src/main/kotlin/org/moire/ultrasonic/fragment/ArtistListFragment.kt
> +        selectFolderHeader!!.setData(
This can be null, when there is no header!
Currently it can throw an exception:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.moire.ultrasonic.debug, PID: 28954
    java.lang.NullPointerException
        at org.moire.ultrasonic.fragment.ArtistListFragment$musicFolderObserver$1.invoke(ArtistListFragment.kt:67)
        at org.moire.ultrasonic.fragment.ArtistListFragment$musicFolderObserver$1.invoke(ArtistListFragment.kt:16)
        at org.moire.ultrasonic.fragment.GenericListFragment$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:6)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

2021-05-16 17:20 UTC, nitehu commented on ultrasonic/src/main/kotlin/org/moire/ultrasonic/fragment/AlbumListFragment.kt
> +    override var folderHeaderEnabled = false
I think this shouldn't be always false here, at least now the folder selector for the albums doesn't work at all...

2021-05-16 19:06 UTC, tzugen commented
Ah, yes, I hadn't tested the folder selectors! They should work as expected now.

2021-05-17 09:34 UTC, nitehu commented
Cool, the folder selector seems to work now!

I've found two new issues unfortunately...
The first is the image shown for album covers when there is no cover on the server. Previously it was this musical note symbol (drawable/unknown_album), and now it is the same as for artists (ic_contact_picture)

And also there is an exception... This happens when I select an album, and then when the songs are displayed, I press back. Only seems to happen when the folder selector is visible.
[exception1.txt](https://github.com/ultrasonic/ultrasonic/files/6492102/exception1.txt)

2021-05-17 15:21 UTC, tzugen commented
This was tricky. Turned out before we were initializing a single instance of the SelectFolderViewHolder, instead of the recommended way of creating a new ViewHolder when the adapter requests it. But for some reason this worked before, but stopped working now.

2021-05-18 07:39 UTC, nitehu approved these changes

2021-05-18 07:41 UTC, nitehu commented
This works very well for me now. I also love the new album icon :)
@ogarcia would you like to check this too? You have better eyes for the UI than me...

2021-05-18 09:01 UTC, ogarcia commented
> This works very well for me now. I also love the new album icon :)
Me too.

> @ogarcia would you like to check this too? You have better eyes for the UI than me...
I think that it works perfect. I don't found any problem. :heart:

2021-05-18 09:44 UTC, merged

2021-05-18 10:02 UTC, tzugen commented
whopwhop!