Target SDK 31
ultrasonic/ultrasonic pull request #731
Opened 2022-04-08 20:59 UTC by hmueller01

make build working with target sdk 31

2022-04-09 06:58 UTC, hmueller01 commented
Ok, now it passes all checks.
The include/exclude xml's are still empty templates. AFAIK this backups everything. And this is different from old Manifest.xml setting. Any suggestions what to exclude?
BTW why was it set to false? Backing up the settings would make sense ...

2022-04-09 07:46 UTC, tzugen commented
> Ok, now it passes all checks. The include/exclude xml's are still empty templates. AFAIK this backups everything. And this is different from old Manifest.xml setting. Any suggestions what to exclude? BTW why was it set to false? Backing up the settings would make sense ...

We should backup settings but not the media files IMO.

Regarding the flag, I think you can take out the switch based on build version. The flag has been around for a while, we can just add it by default. Devices with API lower than 23 will just ignore it.

2022-04-09 08:17 UTC, hmueller01 commented
Current min API is 21. If I leave off the if clause we get this error:

`Field requires API level 23 (current min is 21): android.app.PendingIntent#FLAG_IMMUTABLE`

2022-04-09 08:20 UTC, hmueller01 commented
> We should backup settings but not the media files IMO.

Agreed. Can you help me, what I need to specify in the exclude tag?

2022-04-09 09:12 UTC, tzugen commented
> Current min API is 21. If I leave off the if clause we get this error:
> 
> `Field requires API level 23 (current min is 21): android.app.PendingIntent#FLAG_IMMUTABLE`

OK, then I made a wrong assumption :)

2022-04-09 09:19 UTC, tzugen commented
<exclude domain="file" path="."/>
<include domain="sharedpref" path="."/>
<include domain="database" path="."/>

2022-04-09 09:19 UTC, tzugen commented
<exclude domain="file" path="."/>
<include domain="sharedpref" path="."/>
<include domain="database" path="."/>

2022-04-09 10:12 UTC, hmueller01 commented
I wasn't sure if this `path="."` works or if I need to find out the real names of e.g. the database. So just tried your suggestion.

BTW: `<exclude domain="file" path="."/>` did not work (path "." is not valid). Using `root` instead.

2022-04-12 14:51 UTC, tzugen requested changes
Looks good except the exported=false changes (see comments)

2022-04-12 14:51 UTC, tzugen commented on ultrasonic/src/main/AndroidManifest.xml
> +        <receiver android:name=".receiver.UltrasonicIntentReceiver"
I thinks this needs to be exported, otherwise other apps won't see it.

2022-04-12 14:51 UTC, tzugen commented on ultrasonic/src/main/AndroidManifest.xml
I am unsure if it needs to be exported

2022-04-17 05:05 UTC, tzugen commented
I have merged the changes with the immutability flag. The other things we need to research a bit more i think.

2022-06-16 11:47 UTC, closed without merging

2022-06-16 14:21 UTC, tzugen commented
@hmueller01 Hm, this got automatically closed somehow and I cant reopen it :(
Can you try?

2022-06-16 17:33 UTC, tzugen commented
I think you need to click edit and change the target branch to 'develop'

2022-06-17 06:34 UTC, ogarcia commented
I can't reopen it either. Let's see if @hmueller01 can look at it and if he can't either, the best thing to do is to open a new PR.

2022-06-17 15:27 UTC, hmueller01 commented
Couldn't reopen this. Was easier to create a new PR #754.