Support HTTP basic authentication
ultrasonic/ultrasonic pull request #737
Opened 2022-05-01 07:48 UTC by i-do-cpp

You can now specify HTTP basic authentication credentials in the server URL, e.g. `https://myuser:mypassword@music.server.com`.

closes #351

2022-05-02 16:54 UTC, nitehu commented
Thank you very much for your work!
Your code seems to be fine, unfortunately I can't test that the double authentication works, but I'll execute some regression tests to see if everything is OK and merge this.

2022-05-04 06:25 UTC, tzugen requested changes
Thanks! Also please check if this works in the media3 branch :)

2022-05-04 06:25 UTC, tzugen commented on core/subsonic-api/src/main/kotlin/org/moire/ultrasonic/api/subsonic/SubsonicAPIClient.kt
> +                )
Why instantiate two Builders after each other?
Just remove the build() call from the first builder, reuse it in your logic,
and then call build() in the end.

2022-05-05 05:15 UTC, i-do-cpp commented on core/subsonic-api/src/main/kotlin/org/moire/ultrasonic/api/subsonic/SubsonicAPIClient.kt
> +                )
Can you elaborate which builders you mean? In this interceptor we first use an `HttpUrl.Builder` and then a `Request.Builder`

2022-05-05 09:49 UTC, tzugen commented on core/subsonic-api/src/main/kotlin/org/moire/ultrasonic/api/subsonic/SubsonicAPIClient.kt
> +                )
You are totally right, and quickly reading I didn't see the difference :)
But the reassignment on Line 81 should not be needed. The reason that these methods on the builder returns a Builder ist to enable chaining. The instance of the builder that you call the method on is the same instance that is being returned.

2022-05-05 18:41 UTC, i-do-cpp commented on core/subsonic-api/src/main/kotlin/org/moire/ultrasonic/api/subsonic/SubsonicAPIClient.kt
> +                )
Thank you. I removed the assignment

2022-05-06 05:25 UTC, tzugen approved these changes

2022-05-17 15:48 UTC, nitehu approved these changes
Review OK

2022-05-17 15:49 UTC, merged